config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  resources :posts, only: [:show] do
    member do
      get ':user', to: 'posts#show'
    end
  end

  ActiveAdmin.routes(self)
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mail_log.rb
class MailLog < ApplicationRecord
  belongs_to :post
  has_many :notified_users
  has_many :users, through: :notified_users

end

app/models/notified_user.rb
class NotifiedUser < ApplicationRecord
  belongs_to :mail_log
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  has_and_belongs_to_many :user_groups, optional: true
  has_one :mail_log
  has_one_attached :image
  has_many_attached :files
  after_create :send_notify
  validates_presence_of :title
  validates_length_of :title, :within => 6..50, :too_long => "pick a shorter title", :too_short => "pick a longer title"
  validates_presence_of :text

  private

  def send_notify
    PostLoggerService.send_notify(self)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  has_and_belongs_to_many :user_groups, optional: true

  def name
    email
  end

end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  has_and_belongs_to_many :users, optional: true
  has_and_belongs_to_many :posts, optional: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :warning, :danger, :info
  def authenticate_user!
    redirect_to root_path, info:'You are not allowed there' unless current_user.try(:is_admin?)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, :set_user, only: [:show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.with_attached_image
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    PostLoggerService.update_users(@post,@user )
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.with_attached_image.with_attached_files.find(params[:id])
    end
    def set_user
      @user = User.find_by_email(Base64.urlsafe_decode64(params[:user])) if params[:user]
      sign_in(@user) if @user
      @user = current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def show_attachments?(post)
    return current_user.user_group_ids.any? { |i| post.user_group_ids.include? i} if user_signed_in?
    return false
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>StaffappRework</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

  <body>


    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <%= link_to "StaffAppRework", root_path, :class => 'navbar-brand' %>

        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to "Home", root_path, :class => 'nav-link' %>

            </li>
            <li class="nav-item">
              <%= link_to "Admin", admin_root_path, :class => 'nav-link' %>

            </li>

          </ul>
        </div>
      </div>
    </nav>


<%= yield %>

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; StaffAppRework 2019</p>
          </div>
        </div>
      </div>
    </footer>



  </body>

</html>

app/views/posts/index.html.erb
<!-- Page Header -->
<header class="masthead" style=" ">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Clean Blog</h1>
          <span class="subheading">A Blog Theme by Start Bootstrap</span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>">
            <%= message %>
          </div>
      <% end %>
    </div>
    <div class="col-lg-8 col-md-10 mx-auto">
      <% @posts.each do |post| %>
          <div class="post-preview">
            <%= link_to post_path(post.id) do %>
                <h2 class="post-title" style ="<%= post.mail_log.users.include?(current_user) ? "font-weight: 600" : '' if post.try(:mail_log).try(:users) %>">
                  <%= post.title %>
                </h2>
                <h3 class="post-subtitle">
                  <%= raw post.text %>
                </h3>
            <% end %>
            <p class="post-meta">Posted on <%= post.created_at.to_formatted_s(:short)  %></p>
          </div>
          <hr>
      <% end %>
    </div>
  </div>
</div>

<hr>

app/views/posts/show.html.erb
<header class="masthead" style ="<%= @post.image.attached? ? "background-image: url(#{url_for(@post.image)})" : '' %>">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-heading">
          <h1><%= @post.title %></h1>

          <span class="meta">Posted on <%= @post.created_at.to_formatted_s(:short)  %></span>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Post Content -->
<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>">
              <%= message %>
            </div>
        <% end %>
      </div>
      <div class="col-lg-8 col-md-10 mx-auto">
         <%= raw @post.text %>
      </div>
      <% if show_attachments?(@post) %>
        <div class="col-lg-8 col-md-10 mx-auto">
          <blockquote class="blockquote">Attachments for this post:</blockquote>
          <% @post.files.each do |f| %>
            <p><%= link_to f.filename, rails_blob_path(f, disposition: "attachment") %></p>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</article>

<hr>